const allCountries = [
  "ישראל",
  "ארצות הברית",
  "צרפת",
  "בריטניה",
  "ספרד",
  "פורטוגל",
  "איטליה",
  "גרמניה",
  "הולנד",
  "יפן",
  "יוון",
  "תאילנד",
  "איחוד האמירויות",
  "טורקיה",
  "אוסטריה",
  "שוויץ",
  "צ'כיה",
  "הונגריה",
  "קרואטיה",
  "סינגפור"
];

const allStyles = [
  "טבע",
  "אוכל",
  "נוף",
  "אמנות",
  "היסטוריה",
  "משפחה",
  "לילה",
  "רומנטי",
  "יוקרתי",
  "שקט",
  "צילום",
  "מקומי",
  "צעיר",
  "קניות",
  "חופים",
  "תרבות",
  "מוזיאונים",
  "אדריכלות",
  "טיול רגלי",
  "נוף עירוני",
  "פנורמי",
  "קולינרי",
  "אינסטגרמי",
  "אווירה",
  "טבע עירוני",
  "בילוי",
  "מוזיקה",
  "שווקים",
  "עתיק",
  "הרפתקאות",
  "פארקים",
  "נקודת תצפית",
  "קפה",
  "רחוב יפה",
  "שקיעה",
  "זריחה",
  "חיי לילה",
  "אזור מקומי",
  "טיול זוגי",
  "מרכז העיר"
];

const countryCities = {
  "ישראל": [
    "תל אביב","יפו","ירושלים","חיפה","אילת","טבריה","צפת","נתניה","אשדוד","אשקלון",
    "באר שבע","הרצליה","רמת גן","רחובות","ראשון לציון","פתח תקווה","חולון","בת ים",
    "כפר סבא","רעננה","חדרה","נהריה","עכו"
  ],
  "ארצות הברית": [
    "ניו יורק","לוס אנג'לס","שיקגו","סן פרנסיסקו","מיאמי","לאס וגאס","סיאטל","בוסטון",
    "וושינגטון","סן דייגו","אוסטין","דאלאס","יוסטון","אורלנדו","פילדלפיה","ניו אורלינס"
  ],
  "צרפת": ["פריז","ליון","מרסיי","ניס"],
  "בריטניה": ["לונדון","מנצ'סטר","אדינבורו"],
  "ספרד": ["ברצלונה","מדריד","סביליה","ולנסיה"],
  "פורטוגל": ["ליסבון","פורטו"],
  "איטליה": ["רומא","מילאנו","פירנצה","ונציה"],
  "גרמניה": ["ברלין","מינכן","המבורג"],
  "הולנד": ["אמסטרדם","רוטרדם"],
  "יפן": ["טוקיו","קיוטו","אוסקה"],
  "יוון": ["אתונה","סלוניקי"],
  "תאילנד": ["בנגקוק","צ'יאנג מאי","פוקט"],
  "איחוד האמירויות": ["דובאי","אבו דאבי"],
  "טורקיה": ["איסטנבול","אנטליה"],
  "אוסטריה": ["וינה","זלצבורג"],
  "שוויץ": ["ציריך","לוצרן"],
  "צ'כיה": ["פראג"],
  "הונגריה": ["בודפשט"],
  "קרואטיה": ["דוברובניק","ספליט"],
  "סינגפור": ["סינגפור"]
};

const placesData = [
  {
    id: 1,
    nameHe: "גן העצמאות",
    nameEn: "Independence Park",
    country: "ישראל",
    countryAliases: ["ישראל", "israel", "izr", "israil"],
    city: "תל אביב",
    cityAliases: ["תל אביב", "tel aviv", "tel-aviv"],
    category: "popular",
    styles: ["נוף","טבע","משפחה","שקט","טיול רגלי","טבע עירוני","שקיעה"],
    descriptionHe: "פארק עירוני עם תצפית לים, מדשאות ושבילי הליכה.",
    lat: 32.0894,
    lng: 34.7701,
    timezone: "Asia/Jerusalem",
    interestScore: 92,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.tel-aviv.gov.il"
  },
  {
    id: 2,
    nameHe: "נמל תל אביב",
    nameEn: "Tel Aviv Port",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "תל אביב",
    cityAliases: ["תל אביב", "tel aviv"],
    category: "popular",
    styles: ["אוכל","נוף","בילוי","חיי לילה","קניות","שקיעה"],
    descriptionHe: "אזור חוף תוסס עם מסעדות, טיילת, חנויות ונוף לים.",
    lat: 32.0984,
    lng: 34.7744,
    timezone: "Asia/Jerusalem",
    interestScore: 94,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.tel-aviv.gov.il"
  },
  {
    id: 3,
    nameHe: "שוק הכרמל",
    nameEn: "Carmel Market",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "תל אביב",
    cityAliases: ["תל אביב", "tel aviv"],
    category: "popular",
    styles: ["אוכל","שווקים","מקומי","צעיר","קולינרי","בילוי"],
    descriptionHe: "שוק מרכזי מלא אוכל רחוב, תוצרת טרייה ואווירה מקומית.",
    lat: 32.0684,
    lng: 34.7692,
    timezone: "Asia/Jerusalem",
    interestScore: 95,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.tel-aviv.gov.il"
  },
  {
    id: 4,
    nameHe: "שוק הפשפשים",
    nameEn: "Jaffa Flea Market",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "יפו",
    cityAliases: ["יפו", "jaffa", "yafo"],
    category: "popular",
    styles: ["אוכל","לילה","היסטוריה","שווקים","מקומי","בילוי"],
    descriptionHe: "אזור היסטורי עם חנויות, אוכל ואווירה מיוחדת.",
    lat: 32.0544,
    lng: 34.7562,
    timezone: "Asia/Jerusalem",
    interestScore: 95,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.visit-tel-aviv.com"
  },
  {
    id: 5,
    nameHe: "נמל יפו",
    nameEn: "Jaffa Port",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "יפו",
    cityAliases: ["יפו", "jaffa", "yafo"],
    category: "recommended",
    styles: ["נוף","היסטוריה","רומנטי","טיול זוגי","שקיעה","צילום"],
    descriptionHe: "נמל עתיק עם מסעדות, גלריות ונוף מרהיב לים.",
    lat: 32.0527,
    lng: 34.7504,
    timezone: "Asia/Jerusalem",
    interestScore: 89,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.oldjaffa.co.il"
  },
  {
    id: 6,
    nameHe: "גן סאקר",
    nameEn: "Sacher Park",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "ירושלים",
    cityAliases: ["ירושלים", "jerusalem"],
    category: "recommended",
    styles: ["טבע","משפחה","נוף","שקט","טיול רגלי","פארקים"],
    descriptionHe: "פארק גדול ונעים במרכז העיר לפיקניק, הליכה ומנוחה.",
    lat: 31.7784,
    lng: 35.2057,
    timezone: "Asia/Jerusalem",
    interestScore: 84,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.itraveljerusalem.com"
  },
  {
    id: 7,
    nameHe: "העיר העתיקה",
    nameEn: "Old City Jerusalem",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "ירושלים",
    cityAliases: ["ירושלים", "jerusalem"],
    category: "popular",
    styles: ["היסטוריה","עתיק","תרבות","טיול רגלי","צילום"],
    descriptionHe: "לב ירושלים ההיסטורית עם סמטאות, אתרי דת ושווקים.",
    lat: 31.7767,
    lng: 35.2345,
    timezone: "Asia/Jerusalem",
    interestScore: 99,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.itraveljerusalem.com"
  },
  {
    id: 8,
    nameHe: "טיילת לואי",
    nameEn: "Louis Promenade",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "חיפה",
    cityAliases: ["חיפה", "haifa"],
    category: "popular",
    styles: ["נוף","טבע","רומנטי","פנורמי","צילום","נקודת תצפית"],
    descriptionHe: "טיילת עם נוף פנורמי של מפרץ חיפה והגנים הבהאיים.",
    lat: 32.8183,
    lng: 34.9817,
    timezone: "Asia/Jerusalem",
    interestScore: 88,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.visit-haifa.org"
  },
  {
    id: 9,
    nameHe: "הגנים הבהאיים",
    nameEn: "Bahai Gardens",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "חיפה",
    cityAliases: ["חיפה", "haifa"],
    category: "popular",
    styles: ["טבע","אדריכלות","צילום","שקט","פנורמי"],
    descriptionHe: "גנים מדורגים יפהפיים ואחד האתרים המזוהים עם חיפה.",
    lat: 32.8147,
    lng: 34.9896,
    timezone: "Asia/Jerusalem",
    interestScore: 93,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.ganbahai.org.il"
  },
  {
    id: 10,
    nameHe: "הטיילת הצפונית",
    nameEn: "Eilat Promenade",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "אילת",
    cityAliases: ["אילת", "eilat"],
    category: "popular",
    styles: ["חופים","בילוי","אוכל","משפחה","נוף","שקיעה"],
    descriptionHe: "טיילת מרכזית ליד הים עם מסעדות, חנויות ונוף למפרץ.",
    lat: 29.5569,
    lng: 34.9519,
    timezone: "Asia/Jerusalem",
    interestScore: 90,
    estimatedFlightUsd: 650,
    sourceUrl: "https://eilat.city"
  },
  {
    id: 11,
    nameHe: "פארק טימנע",
    nameEn: "Timna Park",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "אילת",
    cityAliases: ["אילת", "eilat"],
    category: "recommended",
    styles: ["טבע","הרפתקאות","נוף","צילום","עתיק"],
    descriptionHe: "אזור מדברי מרשים עם תצורות סלע ואתרים ארכיאולוגיים.",
    lat: 29.7876,
    lng: 34.9896,
    timezone: "Asia/Jerusalem",
    interestScore: 87,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.parktimna.co.il"
  },

  {
    id: 12,
    nameHe: "סנטרל פארק",
    nameEn: "Central Park",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states", "us", "america", "ארהב", "ארה\"ב"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "new york city", "nyc"],
    category: "popular",
    styles: ["טבע","משפחה","נוף","טיול רגלי","צילום","טבע עירוני","פארקים"],
    descriptionHe: "הפארק המפורסם בלב מנהטן.",
    lat: 40.7829,
    lng: -73.9654,
    timezone: "America/New_York",
    interestScore: 98,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.centralparknyc.org"
  },
  {
    id: 13,
    nameHe: "היי ליין",
    nameEn: "The High Line",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states", "us", "america"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "nyc"],
    category: "recommended",
    styles: ["נוף","אוכל","אמנות","טיול רגלי","צילום","נוף עירוני"],
    descriptionHe: "פארק עילי מיוחד על מסילת רכבת ישנה.",
    lat: 40.7480,
    lng: -74.0048,
    timezone: "America/New_York",
    interestScore: 90,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.thehighline.org"
  },
  {
    id: 14,
    nameHe: "ברוקלין ברידג'",
    nameEn: "Brooklyn Bridge",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "nyc"],
    category: "popular",
    styles: ["צילום","נוף עירוני","טיול רגלי","רומנטי","שקיעה"],
    descriptionHe: "אחד הסמלים הכי מפורסמים של ניו יורק עם נוף מושלם לקו הרקיע.",
    lat: 40.7061,
    lng: -73.9969,
    timezone: "America/New_York",
    interestScore: 96,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.nycgo.com"
  },
  {
    id: 15,
    nameHe: "טיימס סקוור",
    nameEn: "Times Square",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "nyc"],
    category: "popular",
    styles: ["בילוי","לילה","נוף עירוני","צעיר","קניות"],
    descriptionHe: "לב האורות של מנהטן, מלא אנרגיה, שלטים ואנשים.",
    lat: 40.7580,
    lng: -73.9855,
    timezone: "America/New_York",
    interestScore: 97,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.timessquarenyc.org"
  },
  {
    id: 16,
    nameHe: "גריפית' אובזרבטורי",
    nameEn: "Griffith Observatory",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "לוס אנג'לס",
    cityAliases: ["לוס אנג'לס", "los angeles", "la"],
    category: "popular",
    styles: ["נוף","רומנטי","משפחה","פנורמי","צילום","נקודת תצפית"],
    descriptionHe: "תצפית מפורסמת על לוס אנג'לס והשלט של הוליווד.",
    lat: 34.1184,
    lng: -118.3004,
    timezone: "America/Los_Angeles",
    interestScore: 94,
    estimatedFlightUsd: 1200,
    sourceUrl: "https://griffithobservatory.org"
  },
  {
    id: 17,
    nameHe: "דה גטי",
    nameEn: "The Getty",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "לוס אנג'לס",
    cityAliases: ["לוס אנג'לס", "los angeles", "la"],
    category: "recommended",
    styles: ["אמנות","נוף","משפחה","יוקרתי","תרבות","מוזיאונים"],
    descriptionHe: "מוזיאון, גנים ותצפיות נהדרות.",
    lat: 34.0780,
    lng: -118.4741,
    timezone: "America/Los_Angeles",
    interestScore: 87,
    estimatedFlightUsd: 1200,
    sourceUrl: "https://www.getty.edu"
  },
  {
    id: 18,
    nameHe: "סנטה מוניקה פייר",
    nameEn: "Santa Monica Pier",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "לוס אנג'לס",
    cityAliases: ["לוס אנג'לס", "los angeles", "la"],
    category: "popular",
    styles: ["חופים","בילוי","צילום","שקיעה","משפחה"],
    descriptionHe: "מזח מפורסם עם פארק שעשועים קטן ונוף לים.",
    lat: 34.0094,
    lng: -118.4973,
    timezone: "America/Los_Angeles",
    interestScore: 93,
    estimatedFlightUsd: 1200,
    sourceUrl: "https://santamonicapier.org"
  },
  {
    id: 19,
    nameHe: "מילניום פארק",
    nameEn: "Millennium Park",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "שיקגו",
    cityAliases: ["שיקגו", "chicago"],
    category: "popular",
    styles: ["נוף","משפחה","אמנות","צילום","נוף עירוני"],
    descriptionHe: "פארק מפורסם עם Cloud Gate בלב העיר.",
    lat: 41.8826,
    lng: -87.6226,
    timezone: "America/Chicago",
    interestScore: 91,
    estimatedFlightUsd: 1050,
    sourceUrl: "https://www.chicago.gov"
  },
  {
    id: 20,
    nameHe: "גן התה היפני",
    nameEn: "Japanese Tea Garden",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "סן פרנסיסקו",
    cityAliases: ["סן פרנסיסקו", "san francisco", "sf"],
    category: "recommended",
    styles: ["טבע","רומנטי","משפחה","שקט","צילום","פארקים"],
    descriptionHe: "פינה שקטה ומיוחדת בגולדן גייט פארק.",
    lat: 37.7701,
    lng: -122.4702,
    timezone: "America/Los_Angeles",
    interestScore: 86,
    estimatedFlightUsd: 1180,
    sourceUrl: "https://gggp.org"
  },
  {
    id: 21,
    nameHe: "גשר הזהב",
    nameEn: "Golden Gate Bridge",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "סן פרנסיסקו",
    cityAliases: ["סן פרנסיסקו", "san francisco", "sf"],
    category: "popular",
    styles: ["צילום","נוף","פנורמי","טיול רגלי","נקודת תצפית"],
    descriptionHe: "הגשר המפורסם של סן פרנסיסקו עם נקודות צילום מדהימות.",
    lat: 37.8199,
    lng: -122.4783,
    timezone: "America/Los_Angeles",
    interestScore: 98,
    estimatedFlightUsd: 1180,
    sourceUrl: "https://www.goldengate.org"
  },
  {
    id: 22,
    nameHe: "סאות' ביץ'",
    nameEn: "South Beach",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "מיאמי",
    cityAliases: ["מיאמי", "miami"],
    category: "popular",
    styles: ["חופים","לילה","בילוי","צעיר","צילום","שקיעה"],
    descriptionHe: "אזור חופים מפורסם עם אווירה תוססת וארכיטקטורת ארט דקו.",
    lat: 25.7826,
    lng: -80.1341,
    timezone: "America/New_York",
    interestScore: 94,
    estimatedFlightUsd: 1100,
    sourceUrl: "https://www.miamiandbeaches.com"
  },
  {
    id: 23,
    nameHe: "פרנץ' קוורטר",
    nameEn: "French Quarter",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "ניו אורלינס",
    cityAliases: ["ניו אורלינס", "new orleans"],
    category: "recommended",
    styles: ["מוזיקה","לילה","אוכל","היסטוריה","אווירה","מקומי"],
    descriptionHe: "הלב ההיסטורי והחי של ניו אורלינס.",
    lat: 29.9584,
    lng: -90.0644,
    timezone: "America/Chicago",
    interestScore: 89,
    estimatedFlightUsd: 1120,
    sourceUrl: "https://www.neworleans.com"
  },

  {
    id: 24,
    nameHe: "לובר",
    nameEn: "Louvre Museum",
    country: "צרפת",
    countryAliases: ["צרפת", "france", "francia"],
    city: "פריז",
    cityAliases: ["פריז", "paris"],
    category: "popular",
    styles: ["אמנות","היסטוריה","תרבות","מוזיאונים","יוקרתי"],
    descriptionHe: "אחד המוזיאונים המפורסמים בעולם.",
    lat: 48.8606,
    lng: 2.3376,
    timezone: "Europe/Paris",
    interestScore: 99,
    estimatedFlightUsd: 720,
    sourceUrl: "https://www.louvre.fr"
  },
  {
    id: 25,
    nameHe: "תעלת סן מרטן",
    nameEn: "Canal Saint-Martin",
    country: "צרפת",
    countryAliases: ["צרפת", "france"],
    city: "פריז",
    cityAliases: ["פריז", "paris"],
    category: "recommended",
    styles: ["אוכל","לילה","רומנטי","מקומי","טיול רגלי","אווירה"],
    descriptionHe: "אזור מקומי אהוב לטיול, ישיבה ובתי קפה.",
    lat: 48.8722,
    lng: 2.3638,
    timezone: "Europe/Paris",
    interestScore: 85,
    estimatedFlightUsd: 720,
    sourceUrl: "https://parisjetaime.com"
  },
  {
    id: 26,
    nameHe: "מגדל אייפל",
    nameEn: "Eiffel Tower",
    country: "צרפת",
    countryAliases: ["צרפת", "france"],
    city: "פריז",
    cityAliases: ["פריז", "paris"],
    category: "popular",
    styles: ["נוף","רומנטי","צילום","פנורמי","נקודת תצפית"],
    descriptionHe: "הסמל המפורסם ביותר של פריז.",
    lat: 48.8584,
    lng: 2.2945,
    timezone: "Europe/Paris",
    interestScore: 100,
    estimatedFlightUsd: 720,
    sourceUrl: "https://www.toureiffel.paris"
  },

  {
    id: 27,
    nameHe: "הייד פארק",
    nameEn: "Hyde Park",
    country: "בריטניה",
    countryAliases: ["בריטניה", "uk", "united kingdom", "england", "britain"],
    city: "לונדון",
    cityAliases: ["לונדון", "london"],
    category: "popular",
    styles: ["טבע","משפחה","נוף","פארקים","טיול רגלי"],
    descriptionHe: "פארק גדול ומרכזי בלונדון.",
    lat: 51.5073,
    lng: -0.1657,
    timezone: "Europe/London",
    interestScore: 90,
    estimatedFlightUsd: 760,
    sourceUrl: "https://www.royalparks.org.uk"
  },
  {
    id: 28,
    nameHe: "קמדן מרקט",
    nameEn: "Camden Market",
    country: "בריטניה",
    countryAliases: ["בריטניה", "uk", "united kingdom"],
    city: "לונדון",
    cityAliases: ["לונדון", "london"],
    category: "recommended",
    styles: ["אוכל","לילה","אמנות","שווקים","צעיר","בילוי"],
    descriptionHe: "שוק צבעוני ותוסס עם אוכל, חנויות ואווירה צעירה.",
    lat: 51.5416,
    lng: -0.1420,
    timezone: "Europe/London",
    interestScore: 88,
    estimatedFlightUsd: 760,
    sourceUrl: "https://www.camdenmarket.com"
  },
  {
    id: 29,
    nameHe: "סקיי גארדן",
    nameEn: "Sky Garden",
    country: "בריטניה",
    countryAliases: ["בריטניה", "uk", "united kingdom"],
    city: "לונדון",
    cityAliases: ["לונדון", "london"],
    category: "recommended",
    styles: ["נוף","פנורמי","יוקרתי","צילום","נקודת תצפית"],
    descriptionHe: "גן עירוני גבוה עם נוף פנורמי של לונדון.",
    lat: 51.5107,
    lng: -0.0834,
    timezone: "Europe/London",
    interestScore: 86,
    estimatedFlightUsd: 760,
    sourceUrl: "https://skygarden.london"
  },

  {
    id: 30,
    nameHe: "סגרדה פמיליה",
    nameEn: "Sagrada Familia",
    country: "ספרד",
    countryAliases: ["ספרד", "spain", "espana"],
    city: "ברצלונה",
    cityAliases: ["ברצלונה", "barcelona"],
    category: "popular",
    styles: ["אמנות","היסטוריה","אדריכלות","צילום","תרבות"],
    descriptionHe: "אחד האתרים האייקוניים בברצלונה.",
    lat: 41.4036,
    lng: 2.1744,
    timezone: "Europe/Madrid",
    interestScore: 97,
    estimatedFlightUsd: 680,
    sourceUrl: "https://sagradafamilia.org"
  },
  {
    id: 31,
    nameHe: "בונקרס דל כרמל",
    nameEn: "Bunkers del Carmel",
    country: "ספרד",
    countryAliases: ["ספרד", "spain"],
    city: "ברצלונה",
    cityAliases: ["ברצלונה", "barcelona"],
    category: "recommended",
    styles: ["נוף","רומנטי","לילה","צילום","פנורמי","שקיעה"],
    descriptionHe: "נקודת תצפית נהדרת על ברצלונה.",
    lat: 41.4187,
    lng: 2.1527,
    timezone: "Europe/Madrid",
    interestScore: 89,
    estimatedFlightUsd: 680,
    sourceUrl: "https://www.barcelona.cat"
  },

  {
    id: 32,
    nameHe: "ל.אקס פקטורי",
    nameEn: "LX Factory",
    country: "פורטוגל",
    countryAliases: ["פורטוגל", "portugal"],
    city: "ליסבון",
    cityAliases: ["ליסבון", "lisbon", "lisboa"],
    category: "recommended",
    styles: ["אמנות","אוכל","בילוי","צעיר","מקומי","אווירה"],
    descriptionHe: "מרכז יצירתי מלא בתי קפה, חנויות ואווירה אורבנית.",
    lat: 38.7037,
    lng: -9.1784,
    timezone: "Europe/Lisbon",
    interestScore: 87,
    estimatedFlightUsd: 710,
    sourceUrl: "https://lxfactory.com"
  },
  {
    id: 33,
    nameHe: "מיראדורו דה סנטה לוזיה",
    nameEn: "Miradouro de Santa Luzia",
    country: "פורטוגל",
    countryAliases: ["פורטוגל", "portugal"],
    city: "ליסבון",
    cityAliases: ["ליסבון", "lisbon", "lisboa"],
    category: "popular",
    styles: ["נוף","רומנטי","צילום","פנורמי","נקודת תצפית"],
    descriptionHe: "אחת מנקודות התצפית היפות ביותר בליסבון.",
    lat: 38.7110,
    lng: -9.1306,
    timezone: "Europe/Lisbon",
    interestScore: 90,
    estimatedFlightUsd: 710,
    sourceUrl: "https://www.visitportugal.com"
  },

  {
    id: 34,
    nameHe: "קולוסיאום",
    nameEn: "Colosseum",
    country: "איטליה",
    countryAliases: ["איטליה", "italy", "italia"],
    city: "רומא",
    cityAliases: ["רומא", "rome", "roma"],
    category: "popular",
    styles: ["היסטוריה","עתיק","אדריכלות","תרבות","צילום"],
    descriptionHe: "אחד המבנים העתיקים הידועים בעולם.",
    lat: 41.8902,
    lng: 12.4922,
    timezone: "Europe/Rome",
    interestScore: 99,
    estimatedFlightUsd: 730,
    sourceUrl: "https://colosseo.it"
  },
  {
    id: 35,
    nameHe: "טרסטוורה",
    nameEn: "Trastevere",
    country: "איטליה",
    countryAliases: ["איטליה", "italy", "italia"],
    city: "רומא",
    cityAliases: ["רומא", "rome", "roma"],
    category: "recommended",
    styles: ["אוכל","מקומי","לילה","רחוב יפה","אווירה","טיול זוגי"],
    descriptionHe: "רובע מקסים עם סמטאות, מסעדות ואווירה רומאית אמיתית.",
    lat: 41.8897,
    lng: 12.4708,
    timezone: "Europe/Rome",
    interestScore: 91,
    estimatedFlightUsd: 730,
    sourceUrl: "https://www.turismoroma.it"
  },

  {
    id: 36,
    nameHe: "ברנדנבורג גייט",
    nameEn: "Brandenburg Gate",
    country: "גרמניה",
    countryAliases: ["גרמניה", "germany", "deutschland"],
    city: "ברלין",
    cityAliases: ["ברלין", "berlin"],
    category: "popular",
    styles: ["היסטוריה","נוף עירוני","צילום","מרכז העיר"],
    descriptionHe: "אחד הסמלים המוכרים ביותר של ברלין.",
    lat: 52.5163,
    lng: 13.3777,
    timezone: "Europe/Berlin",
    interestScore: 93,
    estimatedFlightUsd: 690,
    sourceUrl: "https://www.visitberlin.de"
  },
  {
    id: 37,
    nameHe: "איסט סייד גלרי",
    nameEn: "East Side Gallery",
    country: "גרמניה",
    countryAliases: ["גרמניה", "germany"],
    city: "ברלין",
    cityAliases: ["ברלין", "berlin"],
    category: "recommended",
    styles: ["אמנות","היסטוריה","צילום","טיול רגלי","אווירה"],
    descriptionHe: "קטע מפורסם של חומת ברלין עם ציורי קיר.",
    lat: 52.5050,
    lng: 13.4399,
    timezone: "Europe/Berlin",
    interestScore: 88,
    estimatedFlightUsd: 690,
    sourceUrl: "https://www.eastsidegallery.berlin"
  },

  {
    id: 38,
    nameHe: "מוזיאון ואן גוך",
    nameEn: "Van Gogh Museum",
    country: "הולנד",
    countryAliases: ["הולנד", "netherlands", "holland"],
    city: "אמסטרדם",
    cityAliases: ["אמסטרדם", "amsterdam"],
    category: "popular",
    styles: ["אמנות","תרבות","מוזיאונים","יוקרתי"],
    descriptionHe: "אחד ממוזיאוני האמנות החשובים באירופה.",
    lat: 52.3584,
    lng: 4.8811,
    timezone: "Europe/Amsterdam",
    interestScore: 94,
    estimatedFlightUsd: 740,
    sourceUrl: "https://www.vangoghmuseum.nl"
  },
  {
    id: 39,
    nameHe: "NDSM Wharf",
    nameEn: "NDSM Wharf",
    country: "הולנד",
    countryAliases: ["הולנד", "netherlands", "holland"],
    city: "אמסטרדם",
    cityAliases: ["אמסטרדם", "amsterdam"],
    category: "recommended",
    styles: ["אמנות","מקומי","צעיר","בילוי","אווירה","צילום"],
    descriptionHe: "אזור יצירתי על קו המים עם אמנות רחוב ואווירה אלטרנטיבית.",
    lat: 52.4003,
    lng: 4.8947,
    timezone: "Europe/Amsterdam",
    interestScore: 85,
    estimatedFlightUsd: 740,
    sourceUrl: "https://www.iamsterdam.com"
  },

  {
    id: 40,
    nameHe: "שיבויה סקראמבל",
    nameEn: "Shibuya Crossing",
    country: "יפן",
    countryAliases: ["יפן", "japan", "nippon"],
    city: "טוקיו",
    cityAliases: ["טוקיו", "tokyo"],
    category: "popular",
    styles: ["נוף עירוני","צעיר","צילום","לילה","בילוי"],
    descriptionHe: "המעבר המפורסם של טוקיו עם אנרגיה אורבנית אדירה.",
    lat: 35.6595,
    lng: 139.7005,
    timezone: "Asia/Tokyo",
    interestScore: 97,
    estimatedFlightUsd: 1250,
    sourceUrl: "https://www.gotokyo.org"
  },
  {
    id: 41,
    nameHe: "קיוסומי גרדן",
    nameEn: "Kiyosumi Gardens",
    country: "יפן",
    countryAliases: ["יפן", "japan"],
    city: "טוקיו",
    cityAliases: ["טוקיו", "tokyo"],
    category: "recommended",
    styles: ["טבע","שקט","רומנטי","צילום","פארקים"],
    descriptionHe: "גן יפני מסורתי ושקט בלב טוקיו.",
    lat: 35.6797,
    lng: 139.8008,
    timezone: "Asia/Tokyo",
    interestScore: 84,
    estimatedFlightUsd: 1250,
    sourceUrl: "https://www.gotokyo.org"
  },
  {
    id: 42,
    nameHe: "פושימי אינארי",
    nameEn: "Fushimi Inari Shrine",
    country: "יפן",
    countryAliases: ["יפן", "japan"],
    city: "קיוטו",
    cityAliases: ["קיוטו", "kyoto"],
    category: "popular",
    styles: ["היסטוריה","טבע","צילום","טיול רגלי","עתיק"],
    descriptionHe: "מקדש מפורסם עם אלפי שערי טורי אדומים.",
    lat: 34.9671,
    lng: 135.7727,
    timezone: "Asia/Tokyo",
    interestScore: 98,
    estimatedFlightUsd: 1250,
    sourceUrl: "https://kyoto.travel"
  },

  {
    id: 43,
    nameHe: "אקרופוליס",
    nameEn: "Acropolis",
    country: "יוון",
    countryAliases: ["יוון", "greece", "hellas"],
    city: "אתונה",
    cityAliases: ["אתונה", "athens"],
    category: "popular",
    styles: ["היסטוריה","עתיק","נוף","צילום","תרבות"],
    descriptionHe: "אחד האתרים העתיקים והחשובים בעולם.",
    lat: 37.9715,
    lng: 23.7257,
    timezone: "Europe/Athens",
    interestScore: 98,
    estimatedFlightUsd: 620,
    sourceUrl: "https://www.thisisathens.org"
  },
  {
    id: 44,
    nameHe: "שכונת פלאקה",
    nameEn: "Plaka",
    country: "יוון",
    countryAliases: ["יוון", "greece"],
    city: "אתונה",
    cityAliases: ["אתונה", "athens"],
    category: "recommended",
    styles: ["אוכל","רחוב יפה","מקומי","טיול זוגי","אווירה"],
    descriptionHe: "שכונה יפהפייה עם סמטאות, מסעדות ואווירה יוונית קלאסית.",
    lat: 37.9723,
    lng: 23.7285,
    timezone: "Europe/Athens",
    interestScore: 88,
    estimatedFlightUsd: 620,
    sourceUrl: "https://www.thisisathens.org"
  },

  {
    id: 45,
    nameHe: "מרינה ביי סנדס סקיי פארק",
    nameEn: "Marina Bay Sands SkyPark",
    country: "סינגפור",
    countryAliases: ["סינגפור", "singapore"],
    city: "סינגפור",
    cityAliases: ["סינגפור", "singapore"],
    category: "popular",
    styles: ["נוף","יוקרתי","פנורמי","צילום","נוף עירוני"],
    descriptionHe: "תצפית אייקונית על קו הרקיע של סינגפור.",
    lat: 1.2834,
    lng: 103.8607,
    timezone: "Asia/Singapore",
    interestScore: 95,
    estimatedFlightUsd: 1180,
    sourceUrl: "https://www.marinabaysands.com"
  },
  {
    id: 46,
    nameHe: "גארדנס ביי דה ביי",
    nameEn: "Gardens by the Bay",
    country: "סינגפור",
    countryAliases: ["סינגפור", "singapore"],
    city: "סינגפור",
    cityAliases: ["סינגפור", "singapore"],
    category: "popular",
    styles: ["טבע","צילום","משפחה","אדריכלות","פנורמי"],
    descriptionHe: "גן עתידני מפורסם עם Supertrees ותצוגות מרהיבות.",
    lat: 1.2816,
    lng: 103.8636,
    timezone: "Asia/Singapore",
    interestScore: 96,
    estimatedFlightUsd: 1180,
    sourceUrl: "https://www.gardensbythebay.com.sg"
  },

  {
    id: 47,
    nameHe: "בורה ח'ליפה",
    nameEn: "Burj Khalifa",
    country: "איחוד האמירויות",
    countryAliases: ["איחוד האמירויות", "uae", "united arab emirates", "dubai"],
    city: "דובאי",
    cityAliases: ["דובאי", "dubai"],
    category: "popular",
    styles: ["יוקרתי","נוף","פנורמי","צילום","נוף עירוני"],
    descriptionHe: "המגדל הגבוה בעולם ואחד הסמלים של דובאי.",
    lat: 25.1972,
    lng: 55.2744,
    timezone: "Asia/Dubai",
    interestScore: 98,
    estimatedFlightUsd: 540,
    sourceUrl: "https://www.burjkhalifa.ae"
  },
  {
    id: 48,
    nameHe: "אל סיף",
    nameEn: "Al Seef",
    country: "איחוד האמירויות",
    countryAliases: ["איחוד האמירויות", "uae", "united arab emirates"],
    city: "דובאי",
    cityAliases: ["דובאי", "dubai"],
    category: "recommended",
    styles: ["מקומי","אוכל","רחוב יפה","אווירה","טיול זוגי"],
    descriptionHe: "אזור נעים על קו המים שמשלב ישן וחדש בדובאי.",
    lat: 25.2635,
    lng: 55.2972,
    timezone: "Asia/Dubai",
    interestScore: 84,
    estimatedFlightUsd: 540,
    sourceUrl: "https://www.visitdubai.com"
  },

  {
    id: 49,
    nameHe: "האגיה סופיה",
    nameEn: "Hagia Sophia",
    country: "טורקיה",
    countryAliases: ["טורקיה", "turkey", "turkiye"],
    city: "איסטנבול",
    cityAliases: ["איסטנבול", "istanbul"],
    category: "popular",
    styles: ["היסטוריה","עתיק","אדריכלות","תרבות","צילום"],
    descriptionHe: "אחד האתרים ההיסטוריים החשובים בעולם.",
    lat: 41.0086,
    lng: 28.9802,
    timezone: "Europe/Istanbul",
    interestScore: 97,
    estimatedFlightUsd: 430,
    sourceUrl: "https://muze.gen.tr"
  },
  {
    id: 50,
    nameHe: "גלאטה טאוור",
    nameEn: "Galata Tower",
    country: "טורקיה",
    countryAliases: ["טורקיה", "turkey", "turkiye"],
    city: "איסטנבול",
    cityAliases: ["איסטנבול", "istanbul"],
    category: "recommended",
    styles: ["נוף","פנורמי","צילום","נקודת תצפית","נוף עירוני"],
    descriptionHe: "מגדל היסטורי עם תצפית נהדרת על איסטנבול.",
    lat: 41.0256,
    lng: 28.9741,
    timezone: "Europe/Istanbul",
    interestScore: 89,
    estimatedFlightUsd: 430,
    sourceUrl: "https://muze.gen.tr"
  }
];
