const allCountries = [
  "ישראל",
  "ארצות הברית",
  "צרפת",
  "בריטניה",
  "ספרד",
  "פורטוגל",
  "איטליה",
  "גרמניה",
  "הולנד",
  "יפן",
  "יוון",
  "תאילנד"
];

const allStyles = [
  "טבע",
  "אוכל",
  "נוף",
  "אמנות",
  "היסטוריה",
  "משפחה",
  "לילה",
  "רומנטי",
  "יוקרתי",
  "שקט",
  "צילום",
  "מקומי",
  "צעיר",
  "קניות",
  "חופים",
  "תרבות",
  "מוזיאונים",
  "אדריכלות",
  "טיול רגלי",
  "נוף עירוני",
  "פנורמי",
  "קולינרי",
  "אינסטגרמי",
  "אווירה",
  "טבע עירוני",
  "בילוי",
  "מוזיקה",
  "שווקים",
  "עתיק",
  "הרפתקאות"
];

const countryCities = {
  "ישראל": [
    "תל אביב",
    "יפו",
    "ירושלים",
    "חיפה",
    "אשדוד",
    "אשקלון",
    "באר שבע",
    "נתניה",
    "הרצליה",
    "רמת גן",
    "רחובות",
    "ראשון לציון",
    "אילת",
    "טבריה",
    "צפת",
    "נהריה",
    "חולון",
    "בת ים",
    "פתח תקווה",
    "רעננה",
    "כפר סבא",
    "חדרה"
  ],
  "ארצות הברית": [
    "ניו יורק",
    "לוס אנג'לס",
    "שיקגו",
    "סן פרנסיסקו",
    "מיאמי",
    "לאס וגאס",
    "סיאטל",
    "בוסטון",
    "וושינגטון",
    "סן דייגו",
    "אוסטין",
    "דאלאס",
    "יוסטון",
    "אורלנדו",
    "פילדלפיה"
  ],
  "צרפת": ["פריז", "ליון", "מרסיי", "ניס"],
  "בריטניה": ["לונדון", "מנצ'סטר", "אדינבורו"],
  "ספרד": ["ברצלונה", "מדריד", "סביליה", "ולנסיה"],
  "פורטוגל": ["ליסבון", "פורטו"],
  "איטליה": ["רומא", "מילאנו", "פירנצה", "ונציה"],
  "גרמניה": ["ברלין", "מינכן", "המבורג"],
  "הולנד": ["אמסטרדם", "רוטרדם"],
  "יפן": ["טוקיו", "קיוטו", "אוסקה"],
  "יוון": ["אתונה", "סלוניקי"],
  "תאילנד": ["בנגקוק", "צ'יאנג מאי", "פוקט"]
};

const placesData = [
  {
    id: 1,
    nameHe: "גן העצמאות",
    nameEn: "Independence Park",
    country: "ישראל",
    countryAliases: ["ישראל", "israel", "izr", "israil"],
    city: "תל אביב",
    cityAliases: ["תל אביב", "tel aviv", "tel-aviv"],
    category: "popular",
    styles: ["נוף", "טבע", "משפחה", "שקט", "טיול רגלי", "טבע עירוני"],
    descriptionHe: "פארק עירוני מוכר עם תצפית לים ונקודות ישיבה נעימות.",
    lat: 32.0894,
    lng: 34.7701,
    timezone: "Asia/Jerusalem",
    interestScore: 92,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.tel-aviv.gov.il"
  },
  {
    id: 2,
    nameHe: "שוק הפשפשים",
    nameEn: "Jaffa Flea Market",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "יפו",
    cityAliases: ["יפו", "jaffa", "yafo"],
    category: "popular",
    styles: ["אוכל", "לילה", "היסטוריה", "שווקים", "מקומי", "בילוי"],
    descriptionHe: "אזור היסטורי עם חנויות, אוכל ואווירה מקומית.",
    lat: 32.0544,
    lng: 34.7562,
    timezone: "Asia/Jerusalem",
    interestScore: 95,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.visit-tel-aviv.com"
  },
  {
    id: 3,
    nameHe: "גן סאקר",
    nameEn: "Sacher Park",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "ירושלים",
    cityAliases: ["ירושלים", "jerusalem"],
    category: "recommended",
    styles: ["טבע", "משפחה", "נוף", "שקט", "טיול רגלי"],
    descriptionHe: "פארק פתוח ונעים במרכז העיר.",
    lat: 31.7784,
    lng: 35.2057,
    timezone: "Asia/Jerusalem",
    interestScore: 84,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.itraveljerusalem.com"
  },
  {
    id: 4,
    nameHe: "טיילת לואי",
    nameEn: "Louis Promenade",
    country: "ישראל",
    countryAliases: ["ישראל", "israel"],
    city: "חיפה",
    cityAliases: ["חיפה", "haifa"],
    category: "popular",
    styles: ["נוף", "טבע", "רומנטי", "פנורמי", "צילום"],
    descriptionHe: "טיילת עם נוף פנורמי מרשים של מפרץ חיפה.",
    lat: 32.8183,
    lng: 34.9817,
    timezone: "Asia/Jerusalem",
    interestScore: 88,
    estimatedFlightUsd: 650,
    sourceUrl: "https://www.visit-haifa.org"
  },
  {
    id: 5,
    nameHe: "סנטרל פארק",
    nameEn: "Central Park",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states", "us", "america", "ארהב", "ארה\"ב"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "new york city", "nyc"],
    category: "popular",
    styles: ["טבע", "משפחה", "נוף", "טיול רגלי", "צילום", "טבע עירוני"],
    descriptionHe: "אחד הפארקים המפורסמים בעולם בלב מנהטן.",
    lat: 40.7829,
    lng: -73.9654,
    timezone: "America/New_York",
    interestScore: 98,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.centralparknyc.org"
  },
  {
    id: 6,
    nameHe: "היי ליין",
    nameEn: "The High Line",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states", "us", "america"],
    city: "ניו יורק",
    cityAliases: ["ניו יורק", "new york", "nyc"],
    category: "recommended",
    styles: ["נוף", "אוכל", "אמנות", "טיול רגלי", "צילום", "נוף עירוני"],
    descriptionHe: "פארק מוגבה ומיוחד על תשתית מסילת רכבת ישנה.",
    lat: 40.7480,
    lng: -74.0048,
    timezone: "America/New_York",
    interestScore: 90,
    estimatedFlightUsd: 980,
    sourceUrl: "https://www.thehighline.org"
  },
  {
    id: 7,
    nameHe: "גריפית' אובזרבטורי",
    nameEn: "Griffith Observatory",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "לוס אנג'לס",
    cityAliases: ["לוס אנג'לס", "los angeles", "la"],
    category: "popular",
    styles: ["נוף", "רומנטי", "משפחה", "פנורמי", "צילום", "נוף עירוני"],
    descriptionHe: "תצפית מפורסמת על לוס אנג'לס והשלט של הוליווד.",
    lat: 34.1184,
    lng: -118.3004,
    timezone: "America/Los_Angeles",
    interestScore: 94,
    estimatedFlightUsd: 1200,
    sourceUrl: "https://griffithobservatory.org"
  },
  {
    id: 8,
    nameHe: "דה גטי",
    nameEn: "The Getty",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "לוס אנג'לס",
    cityAliases: ["לוס אנג'לס", "los angeles", "la"],
    category: "recommended",
    styles: ["אמנות", "נוף", "משפחה", "יוקרתי", "תרבות", "מוזיאונים"],
    descriptionHe: "מוזיאון, גנים ותצפיות נהדרות.",
    lat: 34.0780,
    lng: -118.4741,
    timezone: "America/Los_Angeles",
    interestScore: 87,
    estimatedFlightUsd: 1200,
    sourceUrl: "https://www.getty.edu"
  },
  {
    id: 9,
    nameHe: "מילניום פארק",
    nameEn: "Millennium Park",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "שיקגו",
    cityAliases: ["שיקגו", "chicago"],
    category: "popular",
    styles: ["נוף", "משפחה", "אמנות", "צילום", "נוף עירוני"],
    descriptionHe: "פארק מפורסם עם Cloud Gate בלב העיר.",
    lat: 41.8826,
    lng: -87.6226,
    timezone: "America/Chicago",
    interestScore: 91,
    estimatedFlightUsd: 1050,
    sourceUrl: "https://www.chicago.gov"
  },
  {
    id: 10,
    nameHe: "גן התה היפני",
    nameEn: "Japanese Tea Garden",
    country: "ארצות הברית",
    countryAliases: ["ארצות הברית", "usa", "united states"],
    city: "סן פרנסיסקו",
    cityAliases: ["סן פרנסיסקו", "san francisco", "sf"],
    category: "recommended",
    styles: ["טבע", "רומנטי", "משפחה", "שקט", "צילום"],
    descriptionHe: "פינה שקטה ומיוחדת בגולדן גייט פארק.",
    lat: 37.7701,
    lng: -122.4702,
    timezone: "America/Los_Angeles",
    interestScore: 86,
    estimatedFlightUsd: 1180,
    sourceUrl: "https://gggp.org"
  },
  {
    id: 11,
    nameHe: "לובר",
    nameEn: "Louvre Museum",
    country: "צרפת",
    countryAliases: ["צרפת", "france", "francia"],
    city: "פריז",
    cityAliases: ["פריז", "paris"],
    category: "popular",
    styles: ["אמנות", "היסטוריה", "תרבות", "מוזיאונים", "יוקרתי"],
    descriptionHe: "אחד המוזיאונים המפורסמים בעולם.",
    lat: 48.8606,
    lng: 2.3376,
    timezone: "Europe/Paris",
    interestScore: 99,
    estimatedFlightUsd: 720,
    sourceUrl: "https://www.louvre.fr"
  },
  {
    id: 12,
    nameHe: "תעלת סן מרטן",
    nameEn: "Canal Saint-Martin",
    country: "צרפת",
    countryAliases: ["צרפת", "france"],
    city: "פריז",
    cityAliases: ["פריז", "paris"],
    category: "recommended",
    styles: ["אוכל", "לילה", "רומנטי", "מקומי", "טיול רגלי", "אווירה"],
    descriptionHe: "אזור מקומי אהוב לטיול, ישיבה ובתי קפה.",
    lat: 48.8722,
    lng: 2.3638,
    timezone: "Europe/Paris",
    interestScore: 85,
    estimatedFlightUsd: 720,
    sourceUrl: "https://parisjetaime.com"
  }
];
